name: Setup GO
on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         test: [ '1', '2' ]
#     name: Test Job
    
#     steps: 
#       - name: Checkout code
#         uses: actions/checkout@v5
#       - name: Setup go
#         uses: actions/setup-go@v6
#       - run: echo "matrix run ${{ matrix.test }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version: '1.21'
          cache: false
      - name: Set IMAGE_OS environment variable
        run: echo "IMAGE_OS=$ImageOS" >> $GITHUB_ENV    
      - name: Restore Go cache
        uses: actions/cache/restore@v4
        id: go-cache
        with:
          path: |
            $GOMODCACHE
            $GOCACHE
          key: setup-go-${{ runner.os }}-${{ runner.arch }}-${{ env.IMAGE_OS }}-go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
              setup-go-${{ runner.os }}-${{ runner.arch }}-${{ runner.image }}-go-${{ steps.setup-go.outputs.go-version }}-
              setup-go-
      - name: Download modules
        run: go mod download
      - name: Build
        run: go build ./...
